kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-sample-pipeline2"
spec:
  strategy:
    jenkinsPipelineStrategy:
      type: JenkinsPipeline

spec:
  source:
    git:
      uri: "https://github.com/flozanorht/test-jenkins.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile